import type { Category } from "./categoriesApi";

export const mockCategoryData: Category[] = [
  {
    id: "root-fashion",
    name: "Fashion",
    slug: "fashion",
    parentId: null,
    sortOrder: 1,
    isActive: true,
    isVisible: true,
    description: "Fashion products",
    iconUrl: "",
    imageUrl: "",
    metaTitle: "Fashion",
    metaDescription: "Fashion category",
    metaKeywords: ["fashion"],
    productCount: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    children: [
      {
        id: "mens",
        name: "Men",
        slug: "men",
        parentId: "root-fashion",
        sortOrder: 1,
        isActive: true,
        isVisible: true,
        description: "Men category",
        iconUrl: "",
        imageUrl: "",
        metaTitle: "Men",
        metaDescription: "Men category",
        metaKeywords: ["men"],
        productCount: 3,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        children: [],
      },
      {
        id: "accessories",
        name: "Accessories",
        slug: "accessories",
        parentId: "root-fashion",
        sortOrder: 2,
        isActive: false,
        isVisible: false,
        description: "Accessories",
        iconUrl: "",
        imageUrl: "",
        metaTitle: "Accessories",
        metaDescription: "Accessories category",
        metaKeywords: ["accessories"],
        productCount: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        children: [],
      },
    ],
  },
];

